version: '2'
services:
    app:
        build:
            context: ./go
            dockerfile: Dockerfile.${ENV}
        ports:
            - "8080:8080"
        volumes:
            - ./go/app:/public
        env_file:
            - ./.env
        networks:
            - app-network

    # MySQL database service
    db:
        image: mysql:5.6
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
        env_file:
            - ./.env
        networks:
            - app-network
        volumes:
            - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql

networks:
    app-network:
        driver: bridge